org.gradle.jvmargs=-Xmx1G -Djava.net.preferIPv4Stack=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.21.2)
neo_version=21.1.219
neo_version_range=[21.1.160,)
loader_version_range=[4,)

## Mod Properties
mod_id=cookscollection
mod_name=Cooks Collection
mod_license=All Rights Reserved
mod_version=0.6.0
mod_group_id=com.baisylia.cookscollection
mod_authors=Developer: NCP Bails | Art: Bagels, Raspmary | Contributions: Cassian, Evanbones
mod_description=A Farmer's Delight addon containing various additions.

# Dependencies
farmers_delight_version=1.21.1-1.3.2
#appleskin_version=mc1.21-3.0.4
appleskin_version=3.0.5+mc1.21
jei_version=19.21.0.247
emi_version=1.1.22+1.21.1